#!/usr/bin/env python3
"""Build the Akamai API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'Property Mgr': 'Property',
    'Adaptive Acceleration': 'Adaptive Accel.',
    'Cloud Wrapper': 'Cloud Wrap',
    'Image Manager': 'Image Mgr',
    'App Security': 'App Security',
    'Access Revocation': 'Access Rev.',
    'Client Access': 'Client Acc.',
    'Cloud Access Mgr': 'Cloud Acc.',
    'Aura Content Ctrl': 'Aura Content',
    'Aura Deployment': 'Aura Deploy',
    'Identity Cloud Auth': 'ID Cloud Auth',
    'Identity Cloud Config': 'ID Cloud Cfg',
    'Identity Cloud Hosted': 'ID Cloud Host',
    'Edge Diagnostics': 'Edge Diag.',
    'Fast Purge': 'Fast Purge',
    'Case Mgmt': 'Case Mgmt',
    'Event Center': 'Event Center',
    'Cert Provisioning': 'Cert Provisioning',
    'Firewall Rules': 'FW Rules',
    'Enterprise App Access': 'Enterprise AA',
}

LINES = [
    {
        "name": 'Property & Configuration',
        "color": '#0099CC',
        "stations": [
        ('Property Mgr', (270, 195)),
        ('Edge DNS v2', (440, 175)),
        ('Cloud Wrapper', (620, 165)),
        ('Adaptive Acceleration', (810, 175)),
        ('Cloudlets v3', (1000, 200)),
        ],
    },
    {
        "name": 'Edge Compute',
        "color": '#7B3FE4',
        "stations": [
        ('EdgeWorkers', (270, 310)),
        ('EdgeKV', (430, 285)),
        ('CloudTest', (610, 285)),
        ('DataStream 2', (790, 285)),
        ('Image Manager', (970, 310)),
        ],
    },
    {
        "name": 'Security',
        "color": '#E0245E',
        "stations": [
        ('App Security', (270, 425)),
        ('MFA', (440, 405)),
        ('Access Revocation', (610, 405)),
        ('Client Access', (810, 405)),
        ('Cloud Access Mgr', (1000, 425)),
        ],
    },
    {
        "name": 'Aura LCDN',
        "color": '#0E9D6E',
        "stations": [
        ('Aura Infra', (270, 540)),
        ('Aura Content Ctrl', (450, 515)),
        ('Aura Delivery', (640, 515)),
        ('Aura Deployment', (820, 540)),
        ('Aura Mapping', (1000, 565)),
        ],
    },
    {
        "name": 'Identity & IAM',
        "color": '#1E5BD0',
        "stations": [
        ('IAM v3', (270, 660)),
        ('Identity Cloud Auth', (450, 635)),
        ('Identity Cloud Config', (650, 635)),
        ('Identity Cloud Hosted', (840, 660)),
        ],
    },
    {
        "name": 'Operations',
        "color": '#E68B1F',
        "stations": [
        ('Edge Diagnostics', (270, 770)),
        ('Fast Purge', (450, 745)),
        ('Alerts', (610, 745)),
        ('Case Mgmt', (770, 745)),
        ('Event Center', (920, 770)),
        ],
    },
    {
        "name": 'Specialized',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('ECCU', (790, 815)),
        ('Cert Provisioning', (905, 815)),
        ('Firewall Rules', (790, 815)),
        ('Enterprise App Access', (675, 815)),
        ],
    },
]

URL_OVERRIDES = {
    'Property Mgr': 'https://apis.apis.io/apis/akamai/akamai-property-manager-api-v1/',
    'Edge DNS v2': 'https://apis.apis.io/apis/akamai/akamai-edge-dns-api-v2/',
    'Cloud Wrapper': 'https://apis.apis.io/apis/akamai/akamai-cloud-wrapper-configuration-api/',
    'Adaptive Acceleration': 'https://apis.apis.io/apis/akamai/akamai-adaptive-acceleration-api/',
    'Cloudlets v3': 'https://apis.apis.io/apis/akamai/akamai-cloudlets-api-v3/',
    'EdgeWorkers': 'https://apis.apis.io/apis/akamai/akamai-edgeworkers-api/',
    'EdgeKV': 'https://apis.apis.io/apis/akamai/akamai-edgekv-api/',
    'CloudTest': 'https://apis.apis.io/apis/akamai/akamai-cloudtest-api/',
    'DataStream 2': 'https://apis.apis.io/apis/akamai/akamai-datastream-2-api-v2/',
    'Image Manager': 'https://apis.apis.io/apis/akamai/akamai-image-and-video-manager-api/',
    'App Security': 'https://apis.apis.io/apis/akamai/akamai-application-security-api/',
    'MFA': 'https://apis.apis.io/apis/akamai/akamai-mfa-api/',
    'Access Revocation': 'https://apis.apis.io/apis/akamai/akamai-access-revocation-api/',
    'Client Access': 'https://apis.apis.io/apis/akamai/akamai-client-access-control-api/',
    'Cloud Access Mgr': 'https://apis.apis.io/apis/akamai/akamai-cloud-access-manager-api/',
    'Aura Infra': 'https://apis.apis.io/apis/akamai/akamai-aura-infrastructure-api/',
    'Aura Content Ctrl': 'https://apis.apis.io/apis/akamai/akamai-aura-lcdn-content-control-api/',
    'Aura Delivery': 'https://apis.apis.io/apis/akamai/akamai-aura-lcdn-content-delivery-api/',
    'Aura Deployment': 'https://apis.apis.io/apis/akamai/akamai-aura-lcdn-deployment-api/',
    'Aura Mapping': 'https://apis.apis.io/apis/akamai/akamai-aura-lcdn-mapping-api/',
    'IAM v3': 'https://apis.apis.io/apis/akamai/akamai-identity-and-access-management-api-v3/',
    'Identity Cloud Auth': 'https://apis.apis.io/apis/akamai/akamai-identity-cloud-authentication-api/',
    'Identity Cloud Config': 'https://apis.apis.io/apis/akamai/akamai-identity-cloud-configuration-api/',
    'Identity Cloud Hosted': 'https://apis.apis.io/apis/akamai/akamai-identity-cloud-hosted-login-api/',
    'Edge Diagnostics': 'https://apis.apis.io/apis/akamai/akamai-edge-diagnostics-api/',
    'Fast Purge': 'https://apis.apis.io/apis/akamai/akamai-fast-purge-api/',
    'Alerts': 'https://apis.apis.io/apis/akamai/akamai-alerts-api/',
    'Case Mgmt': 'https://apis.apis.io/apis/akamai/akamai-case-management-api/',
    'Event Center': 'https://apis.apis.io/apis/akamai/akamai-event-center-api/',
    'ECCU': 'https://apis.apis.io/apis/akamai/akamai-enhanced-content-control-utility-eccu-api/',
    'Cert Provisioning': 'https://apis.apis.io/apis/akamai/akamai-certificate-provisioning-system-api/',
    'Firewall Rules': 'https://apis.apis.io/apis/akamai/akamai-firewall-rules-notification-api/',
    'Enterprise App Access': 'https://apis.apis.io/apis/akamai/akamai-enterprise-application-access-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Akamai API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: akamai/openapi · github.com/api-evangelist/akamai',
        out_dir=Path(__file__).resolve().parent,
        out_basename='akamai-subway-map',
        provider_id='akamai',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
