naftiko: 1.0.0-alpha2
info:
  label: 'Akamai: Application Security API — General configuration settings'
  description: 'Akamai: Application Security API — General configuration settings. 11 operations. Lead operation: Akamai Create a configuration. Self-contained Naftiko capability covering
    one Akamai business surface.'
  tags:
  - Akamai
  - Application Security
  - General configuration settings
  created: '2026-05-22'
  modified: '2026-05-22'
binds:
- namespace: env
  keys:
    AKAMAI_API_KEY: AKAMAI_API_KEY
capability:
  consumes:
  - type: http
    namespace: appsec-general-configuration-settings
    baseUri: https://{hostname}/appsec/v1
    description: 'Akamai: Application Security API — General configuration settings business capability. Self-contained, no shared references.'
    resources:
    - name: configs
      path: /configs
      operations:
      - name: postpost-config
        method: POST
        description: Create a configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
      - name: getget-configs
        method: GET
        description: List configurations
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
    - name: configs-configId
      path: /configs/{configId}
      operations:
      - name: getget-config
        method: GET
        description: Get a security configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: includeHostnames
          in: query
          type: boolean
          description: If `true`, include the list of hostnames protected by this security configuration in the production network. If `false`, exclude the list of hostnames protected
            by this security configuration in the
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
      - name: putput-config
        method: PUT
        description: Rename a security configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
      - name: deletedelete-config
        method: DELETE
        description: Delete a configuration
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
    - name: configs-configId-versions
      path: /configs/{configId}/versions
      operations:
      - name: postpost-config-versions
        method: POST
        description: Clone a configuration version
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
      - name: getget-config-versions
        method: GET
        description: List configuration versions
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: page
          in: query
          type: integer
          description: The index of the result page. If the value is `-1`, then pagination is ignored. The default value is `1`.
        - name: pageSize
          in: query
          type: integer
          description: The number of items on each result page. The default value is `25`.
        - name: detail
          in: query
          type: boolean
          description: When `true`, the results contain detailed information on versions. With the default `false`, the results contain summary information on versions.
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
    - name: configs-configId-versions-versionNumber
      path: /configs/{configId}/versions/{versionNumber}
      operations:
      - name: getget-version-number
        method: GET
        description: Get configuration version details
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
      - name: deletedelete-version-number
        method: DELETE
        description: Delete a configuration version
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
    - name: configs-configId-versions-versionNumber-version-notes
      path: /configs/{configId}/versions/{versionNumber}/version-notes
      operations:
      - name: getget-version-notes
        method: GET
        description: Get the version notes
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
      - name: putput-version-notes
        method: PUT
        description: Modify version notes
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
