naftiko: 1.0.0-alpha2
info:
  label: 'Akamai: Certificate Provisioning System API — Deployments'
  description: 'Akamai: Certificate Provisioning System API — Deployments. 4 operations. Lead operation: Akamai Update a deployment schedule. Self-contained Naftiko capability covering
    one Akamai business surface.'
  tags:
  - Akamai
  - CPS
  - Deployments
  created: '2026-05-22'
  modified: '2026-05-22'
binds:
- namespace: env
  keys:
    AKAMAI_API_KEY: AKAMAI_API_KEY
capability:
  consumes:
  - type: http
    namespace: cps-deployments
    baseUri: https://{hostname}/cps/v2
    description: 'Akamai: Certificate Provisioning System API — Deployments business capability. Self-contained, no shared references.'
    resources:
    - name: enrollments-enrollmentId-changes-changeId-deployment-schedul
      path: /enrollments/{enrollmentId}/changes/{changeId}/deployment-schedule
      operations:
      - name: putput-change-deployment-schedule
        method: PUT
        description: Update a deployment schedule
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: enrollments-enrollmentId-deployments
      path: /enrollments/{enrollmentId}/deployments
      operations:
      - name: getget-deployments
        method: GET
        description: List deployments
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
    - name: enrollments-enrollmentId-deployments-production
      path: /enrollments/{enrollmentId}/deployments/production
      operations:
      - name: getget-deployments-production
        method: GET
        description: Get production deployment
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
    - name: enrollments-enrollmentId-deployments-staging
      path: /enrollments/{enrollmentId}/deployments/staging
      operations:
      - name: getget-deployment-staging
        method: GET
        description: Get staging deployment
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: accountSwitchKey
          in: query
          type: string
          description: For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client).
            The Identity and
